(
\disconnected{\bz_0\bh_0\bz_0} + \disconnected{\bar{f}\bz^{}_{\blue{k}\red{}}\bh_0\bz^{\magenta{k}\blue{}\red{}}_{}} + \disconnected{\bar{f}^{2}\bz^{}_{\blue{kl}\red{}}\bh_0\bz^{\magenta{kl}\blue{}\red{}}_{}} + \disconnected{f\bz^{\blue{k}\red{}}_{}\bh_0\bz^{}_{\magenta{k}\blue{}\red{}}} + \disconnected{f\bar{f}\bz^{\blue{k}\red{}}_{\blue{l}\red{}}\bh_0\bz^{\magenta{l}\blue{}\red{}}_{\magenta{k}\blue{}\red{}}} + \disconnected{f^{2}\bz^{\blue{kl}\red{}}_{}\bh_0\bz^{}_{\magenta{kl}\blue{}\red{}}} + \disconnected{\bar{f}\bz_0\bh^{}_{\blue{}\blue{k}\red{}}\bz^{\magenta{}\blue{k}\red{}}_{}}
    \\  &+  % split long equation
\disconnected{\bar{f}^{2}\bz^{}_{\blue{k}\red{}}\bh^{}_{\blue{}\blue{l}\red{}}\bz^{\magenta{k}\blue{l}\red{}}_{}} + \disconnected{f\bz^{k\blue{}\red{}}_{}\bh^{}_{\blue{k}\blue{}\red{}}\bz_0} + \disconnected{f\bar{f}\bz^{\blue{k}\red{}}_{}\bh^{}_{\blue{}\blue{l}\red{}}\bz^{\magenta{}\blue{l}\red{}}_{\magenta{k}\blue{}\red{}}} + \disconnected{f\bar{f}\bz^{k\blue{}\red{}}_{\blue{l}\red{}}\bh^{}_{\blue{k}\blue{}\red{}}\bz^{\magenta{l}\blue{}\red{}}_{}} + \disconnected{f^{2}\bz^{k\blue{l}\red{}}_{}\bh^{}_{\blue{k}\blue{}\red{}}\bz^{}_{\magenta{l}\blue{}\red{}}} + \disconnected{\bar{f}^{2}\bz_0\bh^{}_{\blue{}\blue{kl}\red{}}\bz^{\magenta{}\blue{kl}\red{}}_{}} + f\bar{f}\bz^{k\blue{}\red{}}_{}\bh^{}_{\blue{k}\blue{l}\red{}}\bz^{\magenta{}\blue{l}\red{}}_{}
    \\  &+  % split long equation
f\bar{f}^{2}\bz^{k\blue{}\red{}}_{\blue{l}\red{}}\bh^{}_{\blue{k}\blue{m}\red{}}\bz^{\magenta{l}\blue{m}\red{}}_{} + \disconnected{f^{2}\bz^{kl\blue{}\red{}}_{}\bh^{}_{\blue{kl}\blue{}\red{}}\bz_0} + f^{2}\bar{f}\bz^{k\blue{l}\red{}}_{}\bh^{}_{\blue{k}\blue{m}\red{}}\bz^{\magenta{}\blue{m}\red{}}_{\magenta{l}\blue{}\red{}} + \disconnected{f\bz_0\bh^{\blue{}\blue{k}\red{}}_{}\bz^{}_{\magenta{}\blue{k}\red{}}} + \disconnected{\bar{f}\bz^{}_{k\blue{}\red{}}\bh^{\blue{k}\blue{}\red{}}_{}\bz_0} + \disconnected{f\bar{f}\bz^{}_{\blue{k}\red{}}\bh^{\blue{}\blue{l}\red{}}_{}\bz^{\magenta{k}\blue{}\red{}}_{\magenta{}\blue{l}\red{}}} + \disconnected{\bar{f}^{2}\bz^{}_{k\blue{l}\red{}}\bh^{\blue{k}\blue{}\red{}}_{}\bz^{\magenta{l}\blue{}\red{}}_{}}
    \\  &+  % split long equation
\disconnected{f^{2}\bz^{\blue{k}\red{}}_{}\bh^{\blue{}\blue{l}\red{}}_{}\bz^{}_{\magenta{k}\blue{l}\red{}}} + \disconnected{f\bar{f}\bz^{\blue{k}\red{}}_{l\blue{}\red{}}\bh^{\blue{l}\blue{}\red{}}_{}\bz^{}_{\magenta{k}\blue{}\red{}}} + \disconnected{f\bar{f}\bz_0\bh^{\blue{}\blue{l}\red{}}_{\blue{}\blue{k}\red{}}\bz^{\magenta{}\blue{k}\red{}}_{\magenta{}\blue{l}\red{}}} + \bar{f}^{2}\bz^{}_{k\blue{}\red{}}\bh^{\blue{k}\blue{}\red{}}_{\blue{}\blue{l}\red{}}\bz^{\magenta{}\blue{l}\red{}}_{} + \bar{f}^{3}\bz^{}_{k\blue{l}\red{}}\bh^{\blue{k}\blue{}\red{}}_{\blue{}\blue{m}\red{}}\bz^{\magenta{l}\blue{m}\red{}}_{} + f^{2}\bz^{k\blue{}\red{}}_{}\bh^{\blue{}\blue{l}\red{}}_{\blue{k}\blue{}\red{}}\bz^{}_{\magenta{}\blue{l}\red{}} + \disconnected{f\bar{f}\bz^{k\blue{}\red{}}_{l\blue{}\red{}}\bh^{\blue{l}\blue{}\red{}}_{\blue{k}\blue{}\red{}}\bz_0}
    \\  &+  % split long equation
f\bar{f}^{2}\bz^{\blue{k}\red{}}_{l\blue{}\red{}}\bh^{\blue{l}\blue{}\red{}}_{\blue{}\blue{m}\red{}}\bz^{\magenta{}\blue{m}\red{}}_{\magenta{k}\blue{}\red{}} + f^{2}\bar{f}\bz^{k\blue{}\red{}}_{\blue{l}\red{}}\bh^{\blue{}\blue{m}\red{}}_{\blue{k}\blue{}\red{}}\bz^{\magenta{l}\blue{}\red{}}_{\magenta{}\blue{m}\red{}} + f^{3}\bz^{k\blue{l}\red{}}_{}\bh^{\blue{}\blue{m}\red{}}_{\blue{k}\blue{}\red{}}\bz^{}_{\magenta{l}\blue{m}\red{}} + \disconnected{f^{2}\bz_0\bh^{\blue{}\blue{kl}\red{}}_{}\bz^{}_{\magenta{}\blue{kl}\red{}}} + f\bar{f}\bz^{}_{k\blue{}\red{}}\bh^{\blue{k}\blue{l}\red{}}_{}\bz^{}_{\magenta{}\blue{l}\red{}} + \disconnected{\bar{f}^{2}\bz^{}_{kl\blue{}\red{}}\bh^{\blue{kl}\blue{}\red{}}_{}\bz_0} + f\bar{f}^{2}\bz^{}_{k\blue{l}\red{}}\bh^{\blue{k}\blue{m}\red{}}_{}\bz^{\magenta{l}\blue{}\red{}}_{\magenta{}\blue{m}\red{}}
    \\  &+  % split long equation
\disconnected{f^{2}\bz_0\bh^{\blue{}\blue{kl}\red{}}_{}\bz^{}_{\magenta{}\blue{kl}\red{}}} + f\bar{f}\bz^{}_{k\blue{}\red{}}\bh^{\blue{k}\blue{l}\red{}}_{}\bz^{}_{\magenta{}\blue{l}\red{}} + \disconnected{\bar{f}^{2}\bz^{}_{kl\blue{}\red{}}\bh^{\blue{kl}\blue{}\red{}}_{}\bz_0} + f\bar{f}^{2}\bz^{}_{k\blue{l}\red{}}\bh^{\blue{k}\blue{m}\red{}}_{}\bz^{\magenta{l}\blue{}\red{}}_{\magenta{}\blue{m}\red{}} + f^{2}\bar{f}\bz^{\blue{k}\red{}}_{l\blue{}\red{}}\bh^{\blue{l}\blue{m}\red{}}_{}\bz^{}_{\magenta{k}\blue{m}\red{}}
)